# Generated by Django 4.1.4 on 2023-01-13 00:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productinventory",
            name="sale_price",
        ),
        migrations.AlterField(
            model_name="productinventory",
            name="retail_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="format: maximum price 999.99",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="recommended retail price",
            ),
        ),
    ]
