# Generated by Django 4.1.4 on 2023-01-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsonpromotion",
            name="price_override",
            field=models.BooleanField(default=False),
        ),
    ]
